Sun Oct 18 13:04:42 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 124, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 105, in main
    boss_in_sound.play()
AttributeError: 'NoneType' object has no attribute 'play'

Sun Oct 18 13:56:42 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 151, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 60, in main
    enemyPlane.add_small_enemy(enemys, small_enemys, 15, background_size)
  File "D:\pycharm\pythonPlaneGameProject\enemyPlane.py", line 113, in add_small_enemy
    enemy = smallEnemy(background_size)
  File "D:\pycharm\pythonPlaneGameProject\enemyPlane.py", line 15, in __init__
    self.destory_image.extend([pygame.image.load(".\\images\\enemy1_down1.png").convent_alpha(),
AttributeError: 'pygame.Surface' object has no attribute 'convent_alpha'

Sun Oct 18 13:56:53 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 151, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 60, in main
    enemyPlane.add_small_enemy(enemys, small_enemys, 15, background_size)
  File "D:\pycharm\pythonPlaneGameProject\enemyPlane.py", line 113, in add_small_enemy
    enemy = smallEnemy(background_size)
  File "D:\pycharm\pythonPlaneGameProject\enemyPlane.py", line 15, in __init__
    self.destory_image.extend([pygame.image.load(".\\images\\enemy1_down1.png").convent_alpha(),
AttributeError: 'pygame.Surface' object has no attribute 'convent_alpha'

Sun Oct 18 14:04:36 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 161, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 101, in main
    me.activate = False
NameError: name 'me' is not defined

Sun Oct 18 14:04:52 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 161, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 124, in main
    screen.blit(boss.image1, boss.rect)
pygame.error: display Surface quit

Sun Oct 18 14:05:46 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 161, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 124, in main
    screen.blit(boss.image1, boss.rect)
pygame.error: display Surface quit

Sun Oct 18 14:06:16 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 161, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 124, in main
    screen.blit(boss.image1, boss.rect)
pygame.error: display Surface quit

Sun Oct 18 14:07:38 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 161, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 124, in main
    screen.blit(boss.image1, boss.rect)
pygame.error: display Surface quit

Sun Oct 18 14:07:58 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 161, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 124, in main
    screen.blit(boss.image1, boss.rect)
pygame.error: display Surface quit

Sun Oct 18 21:38:10 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 166, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 82, in main
    if event.key == K_u:
AttributeError: 'Event' object has no attribute 'key'

Mon Oct 19 14:54:10 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 167, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 83, in main
    if event.ke == K_u:
AttributeError: 'Event' object has no attribute 'ke'

Mon Oct 19 19:02:29 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 178, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 86, in main
    hero.use_bullet()
  File "D:\pycharm\pythonPlaneGameProject\heroPlane.py", line 48, in use_bullet
    newBullet = bullet.heroBullet(self.rect, self.background_size)
  File "D:\pycharm\pythonPlaneGameProject\bullet.py", line 17, in __init__
    self.image = pygame.image.load(".\\py_game_test\\magic_bullet")
pygame.error: Couldn't open .\py_game_test\magic_bullet

Mon Oct 19 19:02:42 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 178, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 86, in main
    hero.use_bullet()
  File "D:\pycharm\pythonPlaneGameProject\heroPlane.py", line 48, in use_bullet
    newBullet = bullet.heroBullet(self.rect, self.background_size)
  File "D:\pycharm\pythonPlaneGameProject\bullet.py", line 20, in __init__
    self.rect.left, self.rect.right = rect.rigth, rect.top + 55
AttributeError: 'pygame.Rect' object has no attribute 'rigth'

Mon Oct 19 20:45:48 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 219, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 102, in main
    while running:
UnboundLocalError: local variable 'running' referenced before assignment

Mon Oct 19 20:47:14 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 218, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 125, in main
    keyboard_control()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 60, in keyboard_control
    hero.move_right()
NameError: name 'hero' is not defined

Mon Oct 19 20:47:58 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 219, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 126, in main
    keyboard_control(hero)
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 63, in keyboard_control
    if not (delay % 30):
NameError: name 'delay' is not defined

Tue Oct 20 09:05:29 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 201, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 90, in main
    if bon_num > 0:
UnboundLocalError: local variable 'bon_num' referenced before assignment

Tue Oct 20 11:01:28 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 236, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 167, in main
    collide_test(hero, enemys)
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 72, in collide_test
    if not wudi[0]:
NameError: name 'wudi' is not defined

Tue Oct 20 19:00:57 2020
Traceback (most recent call last):
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 216, in <module>
    main()
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 140, in main
    keyboard_control(hero, wudi, bon_num, delay, enemys)  # 调用键盘控制函数
  File "D:/pycharm/pythonPlaneGameProject/main.py", line 47, in keyboard_control
    hero.use_bullet()
  File "D:\pycharm\pythonPlaneGameProject\heroPlane.py", line 49, in use_bullet
    newBullet = bullet.heroBullet(self.rect, self.background_size)
  File "D:\pycharm\pythonPlaneGameProject\bullet.py", line 17, in __init__
    self.image = pygame.image.load(".\\py_game_test\\magic_bullet.jpg")
pygame.error: Couldn't open .\py_game_test\magic_bullet.jpg

